name: "Sokoban Action"

description: "To play Sokoban game using GitHub Actions"

inputs:
    issue-number:
        description: "Issue number"
        required: true
    issue-user:
        description: "User who created the issue"
        required: true
    move:
        description: "move: $U, $D, $R or $L"
        required: true
    repo-token:
        description: "Token with permissions to do repo things"
        required: true

runs:
    using: "node12"
    main: "index.js"
